language: python

python:
    - "2.7"

env:
    - DJANGO=1.7

install:
    - pip install . --use-mirrors
    - pip install -r sample_project/requirements.txt --use-mirrors

script:
    - python ./sample_project/manage.py test
