language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

env:
    - DJANGO_VERSION=2.2.10 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=3.0.0 SAMPLE_PROJECT=sample_project

branches:
    only:
        - develop

matrix:
    exclude:
        -
            python: "2.7"
            env: DJANGO_VERSION=3.0.0 SAMPLE_PROJECT=sample_project

        -
            python: "3.4"
            env: DJANGO_VERSION=2.2.10 SAMPLE_PROJECT=sample_project

        -
            python: "3.5"
            env: DJANGO_VERSION=2.2.10 SAMPLE_PROJECT=sample_project

        -
            python: "3.6"
            env: DJANGO_VERSION=2.2.10 SAMPLE_PROJECT=sample_project

install:
    - pip install django==$DJANGO_VERSION

script:
    - cd $SAMPLE_PROJECT
    - python manage.py test
